export type ImplementationRiskState = "healthy" | "watch" | "blocked";

export interface ImplementationRiskSignal {
  id: string;
  accountName: string;
  owner: string;
  phase: string;
  blocker: string;
  sponsorConfirmed: boolean;
  daysStalled: number;
  openActions: number;
  revenueAtRisk: number;
  nextStep: string;
}

export const implementationRiskSignals: ImplementationRiskSignal[] = [
  {
    id: "risk_001",
    accountName: "Northstar Logistics",
    owner: "Maya Chen",
    phase: "handoff",
    blocker: "missing migration owner",
    sponsorConfirmed: false,
    daysStalled: 0,
    openActions: 0,
    revenueAtRisk: 18000,
    nextStep: "book implementation checkpoint",
  },
  {
    id: "risk_002",
    accountName: "Beacon Health",
    owner: "Nora Singh",
    phase: "technical_validation",
    blocker: "unclear go-live sequence",
    sponsorConfirmed: true,
    daysStalled: 3,
    openActions: 2,
    revenueAtRisk: 20750,
    nextStep: "send readiness summary",
  },
  {
    id: "risk_003",
    accountName: "Acme Retail",
    owner: "Priya Rao",
    phase: "business_review",
    blocker: "security packet drift",
    sponsorConfirmed: true,
    daysStalled: 6,
    openActions: 4,
    revenueAtRisk: 23500,
    nextStep: "confirm migration runbook",
  },
  {
    id: "risk_004",
    accountName: "Cedar Cloud",
    owner: "Leo Martins",
    phase: "launch_readiness",
    blocker: "data residency question",
    sponsorConfirmed: true,
    daysStalled: 9,
    openActions: 6,
    revenueAtRisk: 26250,
    nextStep: "publish enablement clip",
  },
  {
    id: "risk_005",
    accountName: "Summit Robotics",
    owner: "Maya Chen",
    phase: "handoff",
    blocker: "training owner changed",
    sponsorConfirmed: true,
    daysStalled: 12,
    openActions: 8,
    revenueAtRisk: 29000,
    nextStep: "refresh executive note",
  },
  {
    id: "risk_006",
    accountName: "Juniper Labs",
    owner: "Nora Singh",
    phase: "technical_validation",
    blocker: "pilot telemetry delayed",
    sponsorConfirmed: false,
    daysStalled: 15,
    openActions: 1,
    revenueAtRisk: 31750,
    nextStep: "assign technical owner",
  },
  {
    id: "risk_007",
    accountName: "Atlas Security",
    owner: "Priya Rao",
    phase: "business_review",
    blocker: "missing migration owner",
    sponsorConfirmed: true,
    daysStalled: 18,
    openActions: 3,
    revenueAtRisk: 34500,
    nextStep: "book implementation checkpoint",
  },
  {
    id: "risk_008",
    accountName: "Harbor Foods",
    owner: "Leo Martins",
    phase: "launch_readiness",
    blocker: "unclear go-live sequence",
    sponsorConfirmed: true,
    daysStalled: 21,
    openActions: 5,
    revenueAtRisk: 37250,
    nextStep: "send readiness summary",
  },
  {
    id: "risk_009",
    accountName: "Meridian Travel",
    owner: "Maya Chen",
    phase: "handoff",
    blocker: "security packet drift",
    sponsorConfirmed: true,
    daysStalled: 24,
    openActions: 7,
    revenueAtRisk: 40000,
    nextStep: "confirm migration runbook",
  },
  {
    id: "risk_010",
    accountName: "Copper Grid",
    owner: "Nora Singh",
    phase: "technical_validation",
    blocker: "data residency question",
    sponsorConfirmed: true,
    daysStalled: 27,
    openActions: 0,
    revenueAtRisk: 42750,
    nextStep: "publish enablement clip",
  },
  {
    id: "risk_011",
    accountName: "Nimbus Legal",
    owner: "Priya Rao",
    phase: "business_review",
    blocker: "training owner changed",
    sponsorConfirmed: false,
    daysStalled: 2,
    openActions: 2,
    revenueAtRisk: 45500,
    nextStep: "refresh executive note",
  },
  {
    id: "risk_012",
    accountName: "Aster Analytics",
    owner: "Leo Martins",
    phase: "launch_readiness",
    blocker: "pilot telemetry delayed",
    sponsorConfirmed: true,
    daysStalled: 5,
    openActions: 4,
    revenueAtRisk: 48250,
    nextStep: "assign technical owner",
  },
  {
    id: "risk_013",
    accountName: "Orchid Systems",
    owner: "Maya Chen",
    phase: "handoff",
    blocker: "missing migration owner",
    sponsorConfirmed: true,
    daysStalled: 8,
    openActions: 6,
    revenueAtRisk: 51000,
    nextStep: "book implementation checkpoint",
  },
  {
    id: "risk_014",
    accountName: "Brightline Media",
    owner: "Nora Singh",
    phase: "technical_validation",
    blocker: "unclear go-live sequence",
    sponsorConfirmed: true,
    daysStalled: 11,
    openActions: 8,
    revenueAtRisk: 53750,
    nextStep: "send readiness summary",
  },
  {
    id: "risk_015",
    accountName: "Pioneer Manufacturing",
    owner: "Priya Rao",
    phase: "business_review",
    blocker: "security packet drift",
    sponsorConfirmed: true,
    daysStalled: 14,
    openActions: 1,
    revenueAtRisk: 56500,
    nextStep: "confirm migration runbook",
  },
  {
    id: "risk_016",
    accountName: "SignalWorks",
    owner: "Leo Martins",
    phase: "launch_readiness",
    blocker: "data residency question",
    sponsorConfirmed: false,
    daysStalled: 17,
    openActions: 3,
    revenueAtRisk: 59250,
    nextStep: "publish enablement clip",
  },
  {
    id: "risk_017",
    accountName: "Northstar Logistics",
    owner: "Maya Chen",
    phase: "handoff",
    blocker: "training owner changed",
    sponsorConfirmed: true,
    daysStalled: 20,
    openActions: 5,
    revenueAtRisk: 62000,
    nextStep: "refresh executive note",
  },
  {
    id: "risk_018",
    accountName: "Beacon Health",
    owner: "Nora Singh",
    phase: "technical_validation",
    blocker: "pilot telemetry delayed",
    sponsorConfirmed: true,
    daysStalled: 23,
    openActions: 7,
    revenueAtRisk: 64750,
    nextStep: "assign technical owner",
  },
  {
    id: "risk_019",
    accountName: "Acme Retail",
    owner: "Priya Rao",
    phase: "business_review",
    blocker: "missing migration owner",
    sponsorConfirmed: true,
    daysStalled: 26,
    openActions: 0,
    revenueAtRisk: 67500,
    nextStep: "book implementation checkpoint",
  },
  {
    id: "risk_020",
    accountName: "Cedar Cloud",
    owner: "Leo Martins",
    phase: "launch_readiness",
    blocker: "unclear go-live sequence",
    sponsorConfirmed: true,
    daysStalled: 1,
    openActions: 2,
    revenueAtRisk: 70250,
    nextStep: "send readiness summary",
  },
  {
    id: "risk_021",
    accountName: "Summit Robotics",
    owner: "Maya Chen",
    phase: "handoff",
    blocker: "security packet drift",
    sponsorConfirmed: false,
    daysStalled: 4,
    openActions: 4,
    revenueAtRisk: 73000,
    nextStep: "confirm migration runbook",
  },
  {
    id: "risk_022",
    accountName: "Juniper Labs",
    owner: "Nora Singh",
    phase: "technical_validation",
    blocker: "data residency question",
    sponsorConfirmed: true,
    daysStalled: 7,
    openActions: 6,
    revenueAtRisk: 75750,
    nextStep: "publish enablement clip",
  },
  {
    id: "risk_023",
    accountName: "Atlas Security",
    owner: "Priya Rao",
    phase: "business_review",
    blocker: "training owner changed",
    sponsorConfirmed: true,
    daysStalled: 10,
    openActions: 8,
    revenueAtRisk: 78500,
    nextStep: "refresh executive note",
  },
  {
    id: "risk_024",
    accountName: "Harbor Foods",
    owner: "Leo Martins",
    phase: "launch_readiness",
    blocker: "pilot telemetry delayed",
    sponsorConfirmed: true,
    daysStalled: 13,
    openActions: 1,
    revenueAtRisk: 81250,
    nextStep: "assign technical owner",
  },
  {
    id: "risk_025",
    accountName: "Meridian Travel",
    owner: "Maya Chen",
    phase: "handoff",
    blocker: "missing migration owner",
    sponsorConfirmed: true,
    daysStalled: 16,
    openActions: 3,
    revenueAtRisk: 84000,
    nextStep: "book implementation checkpoint",
  },
  {
    id: "risk_026",
    accountName: "Copper Grid",
    owner: "Nora Singh",
    phase: "technical_validation",
    blocker: "unclear go-live sequence",
    sponsorConfirmed: false,
    daysStalled: 19,
    openActions: 5,
    revenueAtRisk: 86750,
    nextStep: "send readiness summary",
  },
  {
    id: "risk_027",
    accountName: "Nimbus Legal",
    owner: "Priya Rao",
    phase: "business_review",
    blocker: "security packet drift",
    sponsorConfirmed: true,
    daysStalled: 22,
    openActions: 7,
    revenueAtRisk: 89500,
    nextStep: "confirm migration runbook",
  },
  {
    id: "risk_028",
    accountName: "Aster Analytics",
    owner: "Leo Martins",
    phase: "launch_readiness",
    blocker: "data residency question",
    sponsorConfirmed: true,
    daysStalled: 25,
    openActions: 0,
    revenueAtRisk: 92250,
    nextStep: "publish enablement clip",
  },
  {
    id: "risk_029",
    accountName: "Orchid Systems",
    owner: "Maya Chen",
    phase: "handoff",
    blocker: "training owner changed",
    sponsorConfirmed: true,
    daysStalled: 0,
    openActions: 2,
    revenueAtRisk: 95000,
    nextStep: "refresh executive note",
  },
  {
    id: "risk_030",
    accountName: "Brightline Media",
    owner: "Nora Singh",
    phase: "technical_validation",
    blocker: "pilot telemetry delayed",
    sponsorConfirmed: true,
    daysStalled: 3,
    openActions: 4,
    revenueAtRisk: 97750,
    nextStep: "assign technical owner",
  },
  {
    id: "risk_031",
    accountName: "Pioneer Manufacturing",
    owner: "Priya Rao",
    phase: "business_review",
    blocker: "missing migration owner",
    sponsorConfirmed: false,
    daysStalled: 6,
    openActions: 6,
    revenueAtRisk: 100500,
    nextStep: "book implementation checkpoint",
  },
  {
    id: "risk_032",
    accountName: "SignalWorks",
    owner: "Leo Martins",
    phase: "launch_readiness",
    blocker: "unclear go-live sequence",
    sponsorConfirmed: true,
    daysStalled: 9,
    openActions: 8,
    revenueAtRisk: 103250,
    nextStep: "send readiness summary",
  },
  {
    id: "risk_033",
    accountName: "Northstar Logistics",
    owner: "Maya Chen",
    phase: "handoff",
    blocker: "security packet drift",
    sponsorConfirmed: true,
    daysStalled: 12,
    openActions: 1,
    revenueAtRisk: 106000,
    nextStep: "confirm migration runbook",
  },
  {
    id: "risk_034",
    accountName: "Beacon Health",
    owner: "Nora Singh",
    phase: "technical_validation",
    blocker: "data residency question",
    sponsorConfirmed: true,
    daysStalled: 15,
    openActions: 3,
    revenueAtRisk: 108750,
    nextStep: "publish enablement clip",
  },
  {
    id: "risk_035",
    accountName: "Acme Retail",
    owner: "Priya Rao",
    phase: "business_review",
    blocker: "training owner changed",
    sponsorConfirmed: true,
    daysStalled: 18,
    openActions: 5,
    revenueAtRisk: 111500,
    nextStep: "refresh executive note",
  },
  {
    id: "risk_036",
    accountName: "Cedar Cloud",
    owner: "Leo Martins",
    phase: "launch_readiness",
    blocker: "pilot telemetry delayed",
    sponsorConfirmed: false,
    daysStalled: 21,
    openActions: 7,
    revenueAtRisk: 114250,
    nextStep: "assign technical owner",
  },
  {
    id: "risk_037",
    accountName: "Summit Robotics",
    owner: "Maya Chen",
    phase: "handoff",
    blocker: "missing migration owner",
    sponsorConfirmed: true,
    daysStalled: 24,
    openActions: 0,
    revenueAtRisk: 117000,
    nextStep: "book implementation checkpoint",
  },
  {
    id: "risk_038",
    accountName: "Juniper Labs",
    owner: "Nora Singh",
    phase: "technical_validation",
    blocker: "unclear go-live sequence",
    sponsorConfirmed: true,
    daysStalled: 27,
    openActions: 2,
    revenueAtRisk: 119750,
    nextStep: "send readiness summary",
  },
  {
    id: "risk_039",
    accountName: "Atlas Security",
    owner: "Priya Rao",
    phase: "business_review",
    blocker: "security packet drift",
    sponsorConfirmed: true,
    daysStalled: 2,
    openActions: 4,
    revenueAtRisk: 122500,
    nextStep: "confirm migration runbook",
  },
  {
    id: "risk_040",
    accountName: "Harbor Foods",
    owner: "Leo Martins",
    phase: "launch_readiness",
    blocker: "data residency question",
    sponsorConfirmed: true,
    daysStalled: 5,
    openActions: 6,
    revenueAtRisk: 125250,
    nextStep: "publish enablement clip",
  },
  {
    id: "risk_041",
    accountName: "Meridian Travel",
    owner: "Maya Chen",
    phase: "handoff",
    blocker: "training owner changed",
    sponsorConfirmed: false,
    daysStalled: 8,
    openActions: 8,
    revenueAtRisk: 128000,
    nextStep: "refresh executive note",
  },
  {
    id: "risk_042",
    accountName: "Copper Grid",
    owner: "Nora Singh",
    phase: "technical_validation",
    blocker: "pilot telemetry delayed",
    sponsorConfirmed: true,
    daysStalled: 11,
    openActions: 1,
    revenueAtRisk: 130750,
    nextStep: "assign technical owner",
  },
  {
    id: "risk_043",
    accountName: "Nimbus Legal",
    owner: "Priya Rao",
    phase: "business_review",
    blocker: "missing migration owner",
    sponsorConfirmed: true,
    daysStalled: 14,
    openActions: 3,
    revenueAtRisk: 133500,
    nextStep: "book implementation checkpoint",
  },
  {
    id: "risk_044",
    accountName: "Aster Analytics",
    owner: "Leo Martins",
    phase: "launch_readiness",
    blocker: "unclear go-live sequence",
    sponsorConfirmed: true,
    daysStalled: 17,
    openActions: 5,
    revenueAtRisk: 136250,
    nextStep: "send readiness summary",
  },
  {
    id: "risk_045",
    accountName: "Orchid Systems",
    owner: "Maya Chen",
    phase: "handoff",
    blocker: "security packet drift",
    sponsorConfirmed: true,
    daysStalled: 20,
    openActions: 7,
    revenueAtRisk: 139000,
    nextStep: "confirm migration runbook",
  },
  {
    id: "risk_046",
    accountName: "Brightline Media",
    owner: "Nora Singh",
    phase: "technical_validation",
    blocker: "data residency question",
    sponsorConfirmed: false,
    daysStalled: 23,
    openActions: 0,
    revenueAtRisk: 141750,
    nextStep: "publish enablement clip",
  },
  {
    id: "risk_047",
    accountName: "Pioneer Manufacturing",
    owner: "Priya Rao",
    phase: "business_review",
    blocker: "training owner changed",
    sponsorConfirmed: true,
    daysStalled: 26,
    openActions: 2,
    revenueAtRisk: 144500,
    nextStep: "refresh executive note",
  },
  {
    id: "risk_048",
    accountName: "SignalWorks",
    owner: "Leo Martins",
    phase: "launch_readiness",
    blocker: "pilot telemetry delayed",
    sponsorConfirmed: true,
    daysStalled: 1,
    openActions: 4,
    revenueAtRisk: 147250,
    nextStep: "assign technical owner",
  },
  {
    id: "risk_049",
    accountName: "Northstar Logistics",
    owner: "Maya Chen",
    phase: "handoff",
    blocker: "missing migration owner",
    sponsorConfirmed: true,
    daysStalled: 4,
    openActions: 6,
    revenueAtRisk: 150000,
    nextStep: "book implementation checkpoint",
  },
  {
    id: "risk_050",
    accountName: "Beacon Health",
    owner: "Nora Singh",
    phase: "technical_validation",
    blocker: "unclear go-live sequence",
    sponsorConfirmed: true,
    daysStalled: 7,
    openActions: 8,
    revenueAtRisk: 152750,
    nextStep: "send readiness summary",
  },
  {
    id: "risk_051",
    accountName: "Acme Retail",
    owner: "Priya Rao",
    phase: "business_review",
    blocker: "security packet drift",
    sponsorConfirmed: false,
    daysStalled: 10,
    openActions: 1,
    revenueAtRisk: 155500,
    nextStep: "confirm migration runbook",
  },
  {
    id: "risk_052",
    accountName: "Cedar Cloud",
    owner: "Leo Martins",
    phase: "launch_readiness",
    blocker: "data residency question",
    sponsorConfirmed: true,
    daysStalled: 13,
    openActions: 3,
    revenueAtRisk: 158250,
    nextStep: "publish enablement clip",
  },
  {
    id: "risk_053",
    accountName: "Summit Robotics",
    owner: "Maya Chen",
    phase: "handoff",
    blocker: "training owner changed",
    sponsorConfirmed: true,
    daysStalled: 16,
    openActions: 5,
    revenueAtRisk: 161000,
    nextStep: "refresh executive note",
  },
  {
    id: "risk_054",
    accountName: "Juniper Labs",
    owner: "Nora Singh",
    phase: "technical_validation",
    blocker: "pilot telemetry delayed",
    sponsorConfirmed: true,
    daysStalled: 19,
    openActions: 7,
    revenueAtRisk: 163750,
    nextStep: "assign technical owner",
  },
  {
    id: "risk_055",
    accountName: "Atlas Security",
    owner: "Priya Rao",
    phase: "business_review",
    blocker: "missing migration owner",
    sponsorConfirmed: true,
    daysStalled: 22,
    openActions: 0,
    revenueAtRisk: 166500,
    nextStep: "book implementation checkpoint",
  },
  {
    id: "risk_056",
    accountName: "Harbor Foods",
    owner: "Leo Martins",
    phase: "launch_readiness",
    blocker: "unclear go-live sequence",
    sponsorConfirmed: false,
    daysStalled: 25,
    openActions: 2,
    revenueAtRisk: 169250,
    nextStep: "send readiness summary",
  },
  {
    id: "risk_057",
    accountName: "Meridian Travel",
    owner: "Maya Chen",
    phase: "handoff",
    blocker: "security packet drift",
    sponsorConfirmed: true,
    daysStalled: 0,
    openActions: 4,
    revenueAtRisk: 172000,
    nextStep: "confirm migration runbook",
  },
  {
    id: "risk_058",
    accountName: "Copper Grid",
    owner: "Nora Singh",
    phase: "technical_validation",
    blocker: "data residency question",
    sponsorConfirmed: true,
    daysStalled: 3,
    openActions: 6,
    revenueAtRisk: 174750,
    nextStep: "publish enablement clip",
  },
  {
    id: "risk_059",
    accountName: "Nimbus Legal",
    owner: "Priya Rao",
    phase: "business_review",
    blocker: "training owner changed",
    sponsorConfirmed: true,
    daysStalled: 6,
    openActions: 8,
    revenueAtRisk: 177500,
    nextStep: "refresh executive note",
  },
  {
    id: "risk_060",
    accountName: "Aster Analytics",
    owner: "Leo Martins",
    phase: "launch_readiness",
    blocker: "pilot telemetry delayed",
    sponsorConfirmed: true,
    daysStalled: 9,
    openActions: 1,
    revenueAtRisk: 180250,
    nextStep: "assign technical owner",
  },
  {
    id: "risk_061",
    accountName: "Orchid Systems",
    owner: "Maya Chen",
    phase: "handoff",
    blocker: "missing migration owner",
    sponsorConfirmed: false,
    daysStalled: 12,
    openActions: 3,
    revenueAtRisk: 183000,
    nextStep: "book implementation checkpoint",
  },
  {
    id: "risk_062",
    accountName: "Brightline Media",
    owner: "Nora Singh",
    phase: "technical_validation",
    blocker: "unclear go-live sequence",
    sponsorConfirmed: true,
    daysStalled: 15,
    openActions: 5,
    revenueAtRisk: 185750,
    nextStep: "send readiness summary",
  },
  {
    id: "risk_063",
    accountName: "Pioneer Manufacturing",
    owner: "Priya Rao",
    phase: "business_review",
    blocker: "security packet drift",
    sponsorConfirmed: true,
    daysStalled: 18,
    openActions: 7,
    revenueAtRisk: 188500,
    nextStep: "confirm migration runbook",
  },
  {
    id: "risk_064",
    accountName: "SignalWorks",
    owner: "Leo Martins",
    phase: "launch_readiness",
    blocker: "data residency question",
    sponsorConfirmed: true,
    daysStalled: 21,
    openActions: 0,
    revenueAtRisk: 191250,
    nextStep: "publish enablement clip",
  },
  {
    id: "risk_065",
    accountName: "Northstar Logistics",
    owner: "Maya Chen",
    phase: "handoff",
    blocker: "training owner changed",
    sponsorConfirmed: true,
    daysStalled: 24,
    openActions: 2,
    revenueAtRisk: 194000,
    nextStep: "refresh executive note",
  },
  {
    id: "risk_066",
    accountName: "Beacon Health",
    owner: "Nora Singh",
    phase: "technical_validation",
    blocker: "pilot telemetry delayed",
    sponsorConfirmed: false,
    daysStalled: 27,
    openActions: 4,
    revenueAtRisk: 196750,
    nextStep: "assign technical owner",
  },
  {
    id: "risk_067",
    accountName: "Acme Retail",
    owner: "Priya Rao",
    phase: "business_review",
    blocker: "missing migration owner",
    sponsorConfirmed: true,
    daysStalled: 2,
    openActions: 6,
    revenueAtRisk: 199500,
    nextStep: "book implementation checkpoint",
  },
  {
    id: "risk_068",
    accountName: "Cedar Cloud",
    owner: "Leo Martins",
    phase: "launch_readiness",
    blocker: "unclear go-live sequence",
    sponsorConfirmed: true,
    daysStalled: 5,
    openActions: 8,
    revenueAtRisk: 202250,
    nextStep: "send readiness summary",
  },
  {
    id: "risk_069",
    accountName: "Summit Robotics",
    owner: "Maya Chen",
    phase: "handoff",
    blocker: "security packet drift",
    sponsorConfirmed: true,
    daysStalled: 8,
    openActions: 1,
    revenueAtRisk: 205000,
    nextStep: "confirm migration runbook",
  },
  {
    id: "risk_070",
    accountName: "Juniper Labs",
    owner: "Nora Singh",
    phase: "technical_validation",
    blocker: "data residency question",
    sponsorConfirmed: true,
    daysStalled: 11,
    openActions: 3,
    revenueAtRisk: 207750,
    nextStep: "publish enablement clip",
  },
  {
    id: "risk_071",
    accountName: "Atlas Security",
    owner: "Priya Rao",
    phase: "business_review",
    blocker: "training owner changed",
    sponsorConfirmed: false,
    daysStalled: 14,
    openActions: 5,
    revenueAtRisk: 210500,
    nextStep: "refresh executive note",
  },
  {
    id: "risk_072",
    accountName: "Harbor Foods",
    owner: "Leo Martins",
    phase: "launch_readiness",
    blocker: "pilot telemetry delayed",
    sponsorConfirmed: true,
    daysStalled: 17,
    openActions: 7,
    revenueAtRisk: 213250,
    nextStep: "assign technical owner",
  },
];

export function scoreImplementationRisk(signal: ImplementationRiskSignal): number {
  const stalledScore = Math.min(signal.daysStalled, 21) * 3;
  const actionScore = signal.openActions * 8;
  const sponsorScore = signal.sponsorConfirmed ? 0 : 35;
  const revenueScore = signal.revenueAtRisk > 125000 ? 20 : signal.revenueAtRisk > 75000 ? 12 : 4;
  return stalledScore + actionScore + sponsorScore + revenueScore;
}

export function classifyImplementationRisk(signal: ImplementationRiskSignal): ImplementationRiskState {
  const score = scoreImplementationRisk(signal);
  if (score > 110 || (signal.daysStalled > 14 && !signal.sponsorConfirmed)) {
    return "blocked";
  }
  if (score > 70 || signal.openActions > 5) {
    return "watch";
  }
  return "healthy";
}

export function findImplementationRiskByAccount(accountName: string): ImplementationRiskSignal | undefined {
  return implementationRiskSignals.find((signal) => signal.accountName === accountName);
}

export function groupImplementationRiskByOwner(
  signals: ImplementationRiskSignal[] = implementationRiskSignals,
): Record<string, ImplementationRiskSignal[]> {
  return signals.reduce<Record<string, ImplementationRiskSignal[]>>((groups, signal) => {
    groups[signal.owner] ??= [];
    groups[signal.owner].push(signal);
    return groups;
  }, {});
}
