export type RenewalGuardrailState = "expand" | "protect" | "intervene";

export interface RenewalExpansionGuardrail {
  id: string;
  accountName: string;
  owner: string;
  tier: string;
  renewalDate: string;
  expansionSignals: number;
  supportIncidents: number;
  valueProofs: number;
  championActive: boolean;
  executiveAligned: boolean;
  committedNextStep: string;
}

export const renewalExpansionGuardrails: RenewalExpansionGuardrail[] = [
  {
    id: "guardrail_001",
    accountName: "Cedar Cloud",
    owner: "Amelia Ortiz",
    tier: "enterprise",
    renewalDate: "2026-08-05",
    expansionSignals: 0,
    supportIncidents: 0,
    valueProofs: 0,
    championActive: false,
    executiveAligned: true,
    committedNextStep: "share usage proof",
  },
  {
    id: "guardrail_002",
    accountName: "Summit Robotics",
    owner: "Jon Bell",
    tier: "growth",
    renewalDate: "2026-09-06",
    expansionSignals: 7,
    supportIncidents: 5,
    valueProofs: 3,
    championActive: true,
    executiveAligned: false,
    committedNextStep: "schedule renewal desk",
  },
  {
    id: "guardrail_003",
    accountName: "Juniper Labs",
    owner: "Keiko Tan",
    tier: "strategic",
    renewalDate: "2026-10-07",
    expansionSignals: 3,
    supportIncidents: 2,
    valueProofs: 6,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "confirm procurement timeline",
  },
  {
    id: "guardrail_004",
    accountName: "Atlas Security",
    owner: "Samir Patel",
    tier: "enterprise",
    renewalDate: "2026-11-08",
    expansionSignals: 10,
    supportIncidents: 7,
    valueProofs: 2,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "send expansion hypothesis",
  },
  {
    id: "guardrail_005",
    accountName: "Harbor Foods",
    owner: "Amelia Ortiz",
    tier: "growth",
    renewalDate: "2026-12-09",
    expansionSignals: 6,
    supportIncidents: 4,
    valueProofs: 5,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "review support theme",
  },
  {
    id: "guardrail_006",
    accountName: "Meridian Travel",
    owner: "Jon Bell",
    tier: "strategic",
    renewalDate: "2026-08-10",
    expansionSignals: 2,
    supportIncidents: 1,
    valueProofs: 1,
    championActive: true,
    executiveAligned: false,
    committedNextStep: "book executive sponsor call",
  },
  {
    id: "guardrail_007",
    accountName: "Copper Grid",
    owner: "Keiko Tan",
    tier: "enterprise",
    renewalDate: "2026-09-11",
    expansionSignals: 9,
    supportIncidents: 6,
    valueProofs: 4,
    championActive: false,
    executiveAligned: true,
    committedNextStep: "share usage proof",
  },
  {
    id: "guardrail_008",
    accountName: "Nimbus Legal",
    owner: "Samir Patel",
    tier: "growth",
    renewalDate: "2026-10-12",
    expansionSignals: 5,
    supportIncidents: 3,
    valueProofs: 0,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "schedule renewal desk",
  },
  {
    id: "guardrail_009",
    accountName: "Aster Analytics",
    owner: "Amelia Ortiz",
    tier: "strategic",
    renewalDate: "2026-11-13",
    expansionSignals: 1,
    supportIncidents: 0,
    valueProofs: 3,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "confirm procurement timeline",
  },
  {
    id: "guardrail_010",
    accountName: "Orchid Systems",
    owner: "Jon Bell",
    tier: "enterprise",
    renewalDate: "2026-12-14",
    expansionSignals: 8,
    supportIncidents: 5,
    valueProofs: 6,
    championActive: true,
    executiveAligned: false,
    committedNextStep: "send expansion hypothesis",
  },
  {
    id: "guardrail_011",
    accountName: "Brightline Media",
    owner: "Keiko Tan",
    tier: "growth",
    renewalDate: "2026-08-15",
    expansionSignals: 4,
    supportIncidents: 2,
    valueProofs: 2,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "review support theme",
  },
  {
    id: "guardrail_012",
    accountName: "Pioneer Manufacturing",
    owner: "Samir Patel",
    tier: "strategic",
    renewalDate: "2026-09-16",
    expansionSignals: 0,
    supportIncidents: 7,
    valueProofs: 5,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "book executive sponsor call",
  },
  {
    id: "guardrail_013",
    accountName: "SignalWorks",
    owner: "Amelia Ortiz",
    tier: "enterprise",
    renewalDate: "2026-10-17",
    expansionSignals: 7,
    supportIncidents: 4,
    valueProofs: 1,
    championActive: false,
    executiveAligned: true,
    committedNextStep: "share usage proof",
  },
  {
    id: "guardrail_014",
    accountName: "Northstar Logistics",
    owner: "Jon Bell",
    tier: "growth",
    renewalDate: "2026-11-18",
    expansionSignals: 3,
    supportIncidents: 1,
    valueProofs: 4,
    championActive: true,
    executiveAligned: false,
    committedNextStep: "schedule renewal desk",
  },
  {
    id: "guardrail_015",
    accountName: "Beacon Health",
    owner: "Keiko Tan",
    tier: "strategic",
    renewalDate: "2026-12-19",
    expansionSignals: 10,
    supportIncidents: 6,
    valueProofs: 0,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "confirm procurement timeline",
  },
  {
    id: "guardrail_016",
    accountName: "Acme Retail",
    owner: "Samir Patel",
    tier: "enterprise",
    renewalDate: "2026-08-20",
    expansionSignals: 6,
    supportIncidents: 3,
    valueProofs: 3,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "send expansion hypothesis",
  },
  {
    id: "guardrail_017",
    accountName: "Cedar Cloud",
    owner: "Amelia Ortiz",
    tier: "growth",
    renewalDate: "2026-09-21",
    expansionSignals: 2,
    supportIncidents: 0,
    valueProofs: 6,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "review support theme",
  },
  {
    id: "guardrail_018",
    accountName: "Summit Robotics",
    owner: "Jon Bell",
    tier: "strategic",
    renewalDate: "2026-10-22",
    expansionSignals: 9,
    supportIncidents: 5,
    valueProofs: 2,
    championActive: true,
    executiveAligned: false,
    committedNextStep: "book executive sponsor call",
  },
  {
    id: "guardrail_019",
    accountName: "Juniper Labs",
    owner: "Keiko Tan",
    tier: "enterprise",
    renewalDate: "2026-11-23",
    expansionSignals: 5,
    supportIncidents: 2,
    valueProofs: 5,
    championActive: false,
    executiveAligned: true,
    committedNextStep: "share usage proof",
  },
  {
    id: "guardrail_020",
    accountName: "Atlas Security",
    owner: "Samir Patel",
    tier: "growth",
    renewalDate: "2026-12-24",
    expansionSignals: 1,
    supportIncidents: 7,
    valueProofs: 1,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "schedule renewal desk",
  },
  {
    id: "guardrail_021",
    accountName: "Harbor Foods",
    owner: "Amelia Ortiz",
    tier: "strategic",
    renewalDate: "2026-08-25",
    expansionSignals: 8,
    supportIncidents: 4,
    valueProofs: 4,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "confirm procurement timeline",
  },
  {
    id: "guardrail_022",
    accountName: "Meridian Travel",
    owner: "Jon Bell",
    tier: "enterprise",
    renewalDate: "2026-09-26",
    expansionSignals: 4,
    supportIncidents: 1,
    valueProofs: 0,
    championActive: true,
    executiveAligned: false,
    committedNextStep: "send expansion hypothesis",
  },
  {
    id: "guardrail_023",
    accountName: "Copper Grid",
    owner: "Keiko Tan",
    tier: "growth",
    renewalDate: "2026-10-27",
    expansionSignals: 0,
    supportIncidents: 6,
    valueProofs: 3,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "review support theme",
  },
  {
    id: "guardrail_024",
    accountName: "Nimbus Legal",
    owner: "Samir Patel",
    tier: "strategic",
    renewalDate: "2026-11-05",
    expansionSignals: 7,
    supportIncidents: 3,
    valueProofs: 6,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "book executive sponsor call",
  },
  {
    id: "guardrail_025",
    accountName: "Aster Analytics",
    owner: "Amelia Ortiz",
    tier: "enterprise",
    renewalDate: "2026-12-06",
    expansionSignals: 3,
    supportIncidents: 0,
    valueProofs: 2,
    championActive: false,
    executiveAligned: true,
    committedNextStep: "share usage proof",
  },
  {
    id: "guardrail_026",
    accountName: "Orchid Systems",
    owner: "Jon Bell",
    tier: "growth",
    renewalDate: "2026-08-07",
    expansionSignals: 10,
    supportIncidents: 5,
    valueProofs: 5,
    championActive: true,
    executiveAligned: false,
    committedNextStep: "schedule renewal desk",
  },
  {
    id: "guardrail_027",
    accountName: "Brightline Media",
    owner: "Keiko Tan",
    tier: "strategic",
    renewalDate: "2026-09-08",
    expansionSignals: 6,
    supportIncidents: 2,
    valueProofs: 1,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "confirm procurement timeline",
  },
  {
    id: "guardrail_028",
    accountName: "Pioneer Manufacturing",
    owner: "Samir Patel",
    tier: "enterprise",
    renewalDate: "2026-10-09",
    expansionSignals: 2,
    supportIncidents: 7,
    valueProofs: 4,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "send expansion hypothesis",
  },
  {
    id: "guardrail_029",
    accountName: "SignalWorks",
    owner: "Amelia Ortiz",
    tier: "growth",
    renewalDate: "2026-11-10",
    expansionSignals: 9,
    supportIncidents: 4,
    valueProofs: 0,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "review support theme",
  },
  {
    id: "guardrail_030",
    accountName: "Northstar Logistics",
    owner: "Jon Bell",
    tier: "strategic",
    renewalDate: "2026-12-11",
    expansionSignals: 5,
    supportIncidents: 1,
    valueProofs: 3,
    championActive: true,
    executiveAligned: false,
    committedNextStep: "book executive sponsor call",
  },
  {
    id: "guardrail_031",
    accountName: "Beacon Health",
    owner: "Keiko Tan",
    tier: "enterprise",
    renewalDate: "2026-08-12",
    expansionSignals: 1,
    supportIncidents: 6,
    valueProofs: 6,
    championActive: false,
    executiveAligned: true,
    committedNextStep: "share usage proof",
  },
  {
    id: "guardrail_032",
    accountName: "Acme Retail",
    owner: "Samir Patel",
    tier: "growth",
    renewalDate: "2026-09-13",
    expansionSignals: 8,
    supportIncidents: 3,
    valueProofs: 2,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "schedule renewal desk",
  },
  {
    id: "guardrail_033",
    accountName: "Cedar Cloud",
    owner: "Amelia Ortiz",
    tier: "strategic",
    renewalDate: "2026-10-14",
    expansionSignals: 4,
    supportIncidents: 0,
    valueProofs: 5,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "confirm procurement timeline",
  },
  {
    id: "guardrail_034",
    accountName: "Summit Robotics",
    owner: "Jon Bell",
    tier: "enterprise",
    renewalDate: "2026-11-15",
    expansionSignals: 0,
    supportIncidents: 5,
    valueProofs: 1,
    championActive: true,
    executiveAligned: false,
    committedNextStep: "send expansion hypothesis",
  },
  {
    id: "guardrail_035",
    accountName: "Juniper Labs",
    owner: "Keiko Tan",
    tier: "growth",
    renewalDate: "2026-12-16",
    expansionSignals: 7,
    supportIncidents: 2,
    valueProofs: 4,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "review support theme",
  },
  {
    id: "guardrail_036",
    accountName: "Atlas Security",
    owner: "Samir Patel",
    tier: "strategic",
    renewalDate: "2026-08-17",
    expansionSignals: 3,
    supportIncidents: 7,
    valueProofs: 0,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "book executive sponsor call",
  },
  {
    id: "guardrail_037",
    accountName: "Harbor Foods",
    owner: "Amelia Ortiz",
    tier: "enterprise",
    renewalDate: "2026-09-18",
    expansionSignals: 10,
    supportIncidents: 4,
    valueProofs: 3,
    championActive: false,
    executiveAligned: true,
    committedNextStep: "share usage proof",
  },
  {
    id: "guardrail_038",
    accountName: "Meridian Travel",
    owner: "Jon Bell",
    tier: "growth",
    renewalDate: "2026-10-19",
    expansionSignals: 6,
    supportIncidents: 1,
    valueProofs: 6,
    championActive: true,
    executiveAligned: false,
    committedNextStep: "schedule renewal desk",
  },
  {
    id: "guardrail_039",
    accountName: "Copper Grid",
    owner: "Keiko Tan",
    tier: "strategic",
    renewalDate: "2026-11-20",
    expansionSignals: 2,
    supportIncidents: 6,
    valueProofs: 2,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "confirm procurement timeline",
  },
  {
    id: "guardrail_040",
    accountName: "Nimbus Legal",
    owner: "Samir Patel",
    tier: "enterprise",
    renewalDate: "2026-12-21",
    expansionSignals: 9,
    supportIncidents: 3,
    valueProofs: 5,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "send expansion hypothesis",
  },
  {
    id: "guardrail_041",
    accountName: "Aster Analytics",
    owner: "Amelia Ortiz",
    tier: "growth",
    renewalDate: "2026-08-22",
    expansionSignals: 5,
    supportIncidents: 0,
    valueProofs: 1,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "review support theme",
  },
  {
    id: "guardrail_042",
    accountName: "Orchid Systems",
    owner: "Jon Bell",
    tier: "strategic",
    renewalDate: "2026-09-23",
    expansionSignals: 1,
    supportIncidents: 5,
    valueProofs: 4,
    championActive: true,
    executiveAligned: false,
    committedNextStep: "book executive sponsor call",
  },
  {
    id: "guardrail_043",
    accountName: "Brightline Media",
    owner: "Keiko Tan",
    tier: "enterprise",
    renewalDate: "2026-10-24",
    expansionSignals: 8,
    supportIncidents: 2,
    valueProofs: 0,
    championActive: false,
    executiveAligned: true,
    committedNextStep: "share usage proof",
  },
  {
    id: "guardrail_044",
    accountName: "Pioneer Manufacturing",
    owner: "Samir Patel",
    tier: "growth",
    renewalDate: "2026-11-25",
    expansionSignals: 4,
    supportIncidents: 7,
    valueProofs: 3,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "schedule renewal desk",
  },
  {
    id: "guardrail_045",
    accountName: "SignalWorks",
    owner: "Amelia Ortiz",
    tier: "strategic",
    renewalDate: "2026-12-26",
    expansionSignals: 0,
    supportIncidents: 4,
    valueProofs: 6,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "confirm procurement timeline",
  },
  {
    id: "guardrail_046",
    accountName: "Northstar Logistics",
    owner: "Jon Bell",
    tier: "enterprise",
    renewalDate: "2026-08-27",
    expansionSignals: 7,
    supportIncidents: 1,
    valueProofs: 2,
    championActive: true,
    executiveAligned: false,
    committedNextStep: "send expansion hypothesis",
  },
  {
    id: "guardrail_047",
    accountName: "Beacon Health",
    owner: "Keiko Tan",
    tier: "growth",
    renewalDate: "2026-09-05",
    expansionSignals: 3,
    supportIncidents: 6,
    valueProofs: 5,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "review support theme",
  },
  {
    id: "guardrail_048",
    accountName: "Acme Retail",
    owner: "Samir Patel",
    tier: "strategic",
    renewalDate: "2026-10-06",
    expansionSignals: 10,
    supportIncidents: 3,
    valueProofs: 1,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "book executive sponsor call",
  },
  {
    id: "guardrail_049",
    accountName: "Cedar Cloud",
    owner: "Amelia Ortiz",
    tier: "enterprise",
    renewalDate: "2026-11-07",
    expansionSignals: 6,
    supportIncidents: 0,
    valueProofs: 4,
    championActive: false,
    executiveAligned: true,
    committedNextStep: "share usage proof",
  },
  {
    id: "guardrail_050",
    accountName: "Summit Robotics",
    owner: "Jon Bell",
    tier: "growth",
    renewalDate: "2026-12-08",
    expansionSignals: 2,
    supportIncidents: 5,
    valueProofs: 0,
    championActive: true,
    executiveAligned: false,
    committedNextStep: "schedule renewal desk",
  },
  {
    id: "guardrail_051",
    accountName: "Juniper Labs",
    owner: "Keiko Tan",
    tier: "strategic",
    renewalDate: "2026-08-09",
    expansionSignals: 9,
    supportIncidents: 2,
    valueProofs: 3,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "confirm procurement timeline",
  },
  {
    id: "guardrail_052",
    accountName: "Atlas Security",
    owner: "Samir Patel",
    tier: "enterprise",
    renewalDate: "2026-09-10",
    expansionSignals: 5,
    supportIncidents: 7,
    valueProofs: 6,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "send expansion hypothesis",
  },
  {
    id: "guardrail_053",
    accountName: "Harbor Foods",
    owner: "Amelia Ortiz",
    tier: "growth",
    renewalDate: "2026-10-11",
    expansionSignals: 1,
    supportIncidents: 4,
    valueProofs: 2,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "review support theme",
  },
  {
    id: "guardrail_054",
    accountName: "Meridian Travel",
    owner: "Jon Bell",
    tier: "strategic",
    renewalDate: "2026-11-12",
    expansionSignals: 8,
    supportIncidents: 1,
    valueProofs: 5,
    championActive: true,
    executiveAligned: false,
    committedNextStep: "book executive sponsor call",
  },
  {
    id: "guardrail_055",
    accountName: "Copper Grid",
    owner: "Keiko Tan",
    tier: "enterprise",
    renewalDate: "2026-12-13",
    expansionSignals: 4,
    supportIncidents: 6,
    valueProofs: 1,
    championActive: false,
    executiveAligned: true,
    committedNextStep: "share usage proof",
  },
  {
    id: "guardrail_056",
    accountName: "Nimbus Legal",
    owner: "Samir Patel",
    tier: "growth",
    renewalDate: "2026-08-14",
    expansionSignals: 0,
    supportIncidents: 3,
    valueProofs: 4,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "schedule renewal desk",
  },
  {
    id: "guardrail_057",
    accountName: "Aster Analytics",
    owner: "Amelia Ortiz",
    tier: "strategic",
    renewalDate: "2026-09-15",
    expansionSignals: 7,
    supportIncidents: 0,
    valueProofs: 0,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "confirm procurement timeline",
  },
  {
    id: "guardrail_058",
    accountName: "Orchid Systems",
    owner: "Jon Bell",
    tier: "enterprise",
    renewalDate: "2026-10-16",
    expansionSignals: 3,
    supportIncidents: 5,
    valueProofs: 3,
    championActive: true,
    executiveAligned: false,
    committedNextStep: "send expansion hypothesis",
  },
  {
    id: "guardrail_059",
    accountName: "Brightline Media",
    owner: "Keiko Tan",
    tier: "growth",
    renewalDate: "2026-11-17",
    expansionSignals: 10,
    supportIncidents: 2,
    valueProofs: 6,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "review support theme",
  },
  {
    id: "guardrail_060",
    accountName: "Pioneer Manufacturing",
    owner: "Samir Patel",
    tier: "strategic",
    renewalDate: "2026-12-18",
    expansionSignals: 6,
    supportIncidents: 7,
    valueProofs: 2,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "book executive sponsor call",
  },
  {
    id: "guardrail_061",
    accountName: "SignalWorks",
    owner: "Amelia Ortiz",
    tier: "enterprise",
    renewalDate: "2026-08-19",
    expansionSignals: 2,
    supportIncidents: 4,
    valueProofs: 5,
    championActive: false,
    executiveAligned: true,
    committedNextStep: "share usage proof",
  },
  {
    id: "guardrail_062",
    accountName: "Northstar Logistics",
    owner: "Jon Bell",
    tier: "growth",
    renewalDate: "2026-09-20",
    expansionSignals: 9,
    supportIncidents: 1,
    valueProofs: 1,
    championActive: true,
    executiveAligned: false,
    committedNextStep: "schedule renewal desk",
  },
  {
    id: "guardrail_063",
    accountName: "Beacon Health",
    owner: "Keiko Tan",
    tier: "strategic",
    renewalDate: "2026-10-21",
    expansionSignals: 5,
    supportIncidents: 6,
    valueProofs: 4,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "confirm procurement timeline",
  },
  {
    id: "guardrail_064",
    accountName: "Acme Retail",
    owner: "Samir Patel",
    tier: "enterprise",
    renewalDate: "2026-11-22",
    expansionSignals: 1,
    supportIncidents: 3,
    valueProofs: 0,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "send expansion hypothesis",
  },
  {
    id: "guardrail_065",
    accountName: "Cedar Cloud",
    owner: "Amelia Ortiz",
    tier: "growth",
    renewalDate: "2026-12-23",
    expansionSignals: 8,
    supportIncidents: 0,
    valueProofs: 3,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "review support theme",
  },
  {
    id: "guardrail_066",
    accountName: "Summit Robotics",
    owner: "Jon Bell",
    tier: "strategic",
    renewalDate: "2026-08-24",
    expansionSignals: 4,
    supportIncidents: 5,
    valueProofs: 6,
    championActive: true,
    executiveAligned: false,
    committedNextStep: "book executive sponsor call",
  },
  {
    id: "guardrail_067",
    accountName: "Juniper Labs",
    owner: "Keiko Tan",
    tier: "enterprise",
    renewalDate: "2026-09-25",
    expansionSignals: 0,
    supportIncidents: 2,
    valueProofs: 2,
    championActive: false,
    executiveAligned: true,
    committedNextStep: "share usage proof",
  },
  {
    id: "guardrail_068",
    accountName: "Atlas Security",
    owner: "Samir Patel",
    tier: "growth",
    renewalDate: "2026-10-26",
    expansionSignals: 7,
    supportIncidents: 7,
    valueProofs: 5,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "schedule renewal desk",
  },
  {
    id: "guardrail_069",
    accountName: "Harbor Foods",
    owner: "Amelia Ortiz",
    tier: "strategic",
    renewalDate: "2026-11-27",
    expansionSignals: 3,
    supportIncidents: 4,
    valueProofs: 1,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "confirm procurement timeline",
  },
  {
    id: "guardrail_070",
    accountName: "Meridian Travel",
    owner: "Jon Bell",
    tier: "enterprise",
    renewalDate: "2026-12-05",
    expansionSignals: 10,
    supportIncidents: 1,
    valueProofs: 4,
    championActive: true,
    executiveAligned: false,
    committedNextStep: "send expansion hypothesis",
  },
  {
    id: "guardrail_071",
    accountName: "Copper Grid",
    owner: "Keiko Tan",
    tier: "growth",
    renewalDate: "2026-08-06",
    expansionSignals: 6,
    supportIncidents: 6,
    valueProofs: 0,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "review support theme",
  },
  {
    id: "guardrail_072",
    accountName: "Nimbus Legal",
    owner: "Samir Patel",
    tier: "strategic",
    renewalDate: "2026-09-07",
    expansionSignals: 2,
    supportIncidents: 3,
    valueProofs: 3,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "book executive sponsor call",
  },
  {
    id: "guardrail_073",
    accountName: "Aster Analytics",
    owner: "Amelia Ortiz",
    tier: "enterprise",
    renewalDate: "2026-10-08",
    expansionSignals: 9,
    supportIncidents: 0,
    valueProofs: 6,
    championActive: false,
    executiveAligned: true,
    committedNextStep: "share usage proof",
  },
  {
    id: "guardrail_074",
    accountName: "Orchid Systems",
    owner: "Jon Bell",
    tier: "growth",
    renewalDate: "2026-11-09",
    expansionSignals: 5,
    supportIncidents: 5,
    valueProofs: 2,
    championActive: true,
    executiveAligned: false,
    committedNextStep: "schedule renewal desk",
  },
  {
    id: "guardrail_075",
    accountName: "Brightline Media",
    owner: "Keiko Tan",
    tier: "strategic",
    renewalDate: "2026-12-10",
    expansionSignals: 1,
    supportIncidents: 2,
    valueProofs: 5,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "confirm procurement timeline",
  },
  {
    id: "guardrail_076",
    accountName: "Pioneer Manufacturing",
    owner: "Samir Patel",
    tier: "enterprise",
    renewalDate: "2026-08-11",
    expansionSignals: 8,
    supportIncidents: 7,
    valueProofs: 1,
    championActive: true,
    executiveAligned: true,
    committedNextStep: "send expansion hypothesis",
  },
];

export function daysUntilRenewal(
  renewalDate: string,
  now = new Date("2026-08-02T00:00:00.000Z"),
): number {
  const target = new Date(renewalDate + "T00:00:00.000Z");
  return Math.ceil((target.getTime() - now.getTime()) / 86_400_000);
}

export function scoreRenewalGuardrail(guardrail: RenewalExpansionGuardrail): number {
  const timingPressure = Math.max(0, 45 - daysUntilRenewal(guardrail.renewalDate));
  const supportPressure = guardrail.supportIncidents * 9;
  const proofRelief = guardrail.valueProofs * 7;
  const championPenalty = guardrail.championActive ? 0 : 24;
  const executivePenalty = guardrail.executiveAligned ? 0 : 18;
  return timingPressure + supportPressure + championPenalty + executivePenalty - proofRelief;
}

export function classifyRenewalGuardrail(guardrail: RenewalExpansionGuardrail): RenewalGuardrailState {
  const score = scoreRenewalGuardrail(guardrail);
  if (score > 55 || (!guardrail.championActive && guardrail.supportIncidents > 3)) {
    return "intervene";
  }
  if (score > 24 || guardrail.expansionSignals < 2) {
    return "protect";
  }
  return "expand";
}

export function findRenewalGuardrailByAccount(accountName: string): RenewalExpansionGuardrail | undefined {
  return renewalExpansionGuardrails.find((guardrail) => guardrail.accountName === accountName);
}

export function groupRenewalGuardrailsByTier(
  guardrails: RenewalExpansionGuardrail[] = renewalExpansionGuardrails,
): Record<string, RenewalExpansionGuardrail[]> {
  return guardrails.reduce<Record<string, RenewalExpansionGuardrail[]>>((groups, guardrail) => {
    groups[guardrail.tier] ??= [];
    groups[guardrail.tier].push(guardrail);
    return groups;
  }, {});
}
