export type PricingApprovalStage = "rep-proposed" | "manager-review" | "finance-review" | "approved";

export interface PricingConcessionScenario {
	readonly id: string;
	readonly account: string;
	readonly owner: string;
	readonly approvalStage: PricingApprovalStage;
	readonly discountPercent: number;
	readonly competitorMentioned: boolean;
	readonly valueProof: string;
	readonly nextAction: string;
}

export interface PricingConcessionSummary {
	readonly scenarios: number;
	readonly averageDiscount: number;
	readonly financeReview: number;
	readonly competitorPressure: number;
	readonly owners: readonly string[];
	readonly requiredActions: readonly string[];
}

export const pricingConcessionScenarios: readonly PricingConcessionScenario[] = [
	{
		id: "pricing-concession-001",
		account: "Cedar Cloud",
		owner: "Amelia",
		approvalStage: "rep-proposed",
		discountPercent: 5,
		competitorMentioned: true,
		valueProof: "usage trend",
		nextAction: "attach value proof",
	},
	{
		id: "pricing-concession-002",
		account: "Summit Robotics",
		owner: "Samir",
		approvalStage: "manager-review",
		discountPercent: 8,
		competitorMentioned: false,
		valueProof: "pilot win",
		nextAction: "request manager approval",
	},
	{
		id: "pricing-concession-003",
		account: "Juniper Labs",
		owner: "Keiko",
		approvalStage: "finance-review",
		discountPercent: 11,
		competitorMentioned: false,
		valueProof: "security proof",
		nextAction: "confirm procurement owner",
	},
	{
		id: "pricing-concession-004",
		account: "Atlas Security",
		owner: "Leo",
		approvalStage: "approved",
		discountPercent: 14,
		competitorMentioned: true,
		valueProof: "executive case",
		nextAction: "restate mutual plan milestone",
	},
	{
		id: "pricing-concession-005",
		account: "Meridian Travel",
		owner: "Amelia",
		approvalStage: "rep-proposed",
		discountPercent: 17,
		competitorMentioned: false,
		valueProof: "usage trend",
		nextAction: "attach value proof",
	},
	{
		id: "pricing-concession-006",
		account: "Copper Grid",
		owner: "Samir",
		approvalStage: "manager-review",
		discountPercent: 20,
		competitorMentioned: false,
		valueProof: "pilot win",
		nextAction: "request manager approval",
	},
	{
		id: "pricing-concession-007",
		account: "Nimbus Legal",
		owner: "Keiko",
		approvalStage: "finance-review",
		discountPercent: 23,
		competitorMentioned: true,
		valueProof: "security proof",
		nextAction: "confirm procurement owner",
	},
	{
		id: "pricing-concession-008",
		account: "Aster Analytics",
		owner: "Leo",
		approvalStage: "approved",
		discountPercent: 26,
		competitorMentioned: false,
		valueProof: "executive case",
		nextAction: "restate mutual plan milestone",
	},
	{
		id: "pricing-concession-009",
		account: "Brightline Media",
		owner: "Amelia",
		approvalStage: "rep-proposed",
		discountPercent: 29,
		competitorMentioned: false,
		valueProof: "usage trend",
		nextAction: "attach value proof",
	},
	{
		id: "pricing-concession-010",
		account: "Pioneer Manufacturing",
		owner: "Samir",
		approvalStage: "manager-review",
		discountPercent: 32,
		competitorMentioned: true,
		valueProof: "pilot win",
		nextAction: "request manager approval",
	},
	{
		id: "pricing-concession-011",
		account: "Northstar Health",
		owner: "Keiko",
		approvalStage: "finance-review",
		discountPercent: 35,
		competitorMentioned: false,
		valueProof: "security proof",
		nextAction: "confirm procurement owner",
	},
	{
		id: "pricing-concession-012",
		account: "Harbor Ledger",
		owner: "Leo",
		approvalStage: "approved",
		discountPercent: 38,
		competitorMentioned: false,
		valueProof: "executive case",
		nextAction: "restate mutual plan milestone",
	},
	{
		id: "pricing-concession-013",
		account: "Cedar Cloud",
		owner: "Amelia",
		approvalStage: "rep-proposed",
		discountPercent: 7,
		competitorMentioned: true,
		valueProof: "usage trend",
		nextAction: "attach value proof",
	},
	{
		id: "pricing-concession-014",
		account: "Summit Robotics",
		owner: "Samir",
		approvalStage: "manager-review",
		discountPercent: 10,
		competitorMentioned: false,
		valueProof: "pilot win",
		nextAction: "request manager approval",
	},
	{
		id: "pricing-concession-015",
		account: "Juniper Labs",
		owner: "Keiko",
		approvalStage: "finance-review",
		discountPercent: 13,
		competitorMentioned: false,
		valueProof: "security proof",
		nextAction: "confirm procurement owner",
	},
	{
		id: "pricing-concession-016",
		account: "Atlas Security",
		owner: "Leo",
		approvalStage: "approved",
		discountPercent: 16,
		competitorMentioned: true,
		valueProof: "executive case",
		nextAction: "restate mutual plan milestone",
	},
	{
		id: "pricing-concession-017",
		account: "Meridian Travel",
		owner: "Amelia",
		approvalStage: "rep-proposed",
		discountPercent: 19,
		competitorMentioned: false,
		valueProof: "usage trend",
		nextAction: "attach value proof",
	},
	{
		id: "pricing-concession-018",
		account: "Copper Grid",
		owner: "Samir",
		approvalStage: "manager-review",
		discountPercent: 22,
		competitorMentioned: false,
		valueProof: "pilot win",
		nextAction: "request manager approval",
	},
	{
		id: "pricing-concession-019",
		account: "Nimbus Legal",
		owner: "Keiko",
		approvalStage: "finance-review",
		discountPercent: 25,
		competitorMentioned: true,
		valueProof: "security proof",
		nextAction: "confirm procurement owner",
	},
	{
		id: "pricing-concession-020",
		account: "Aster Analytics",
		owner: "Leo",
		approvalStage: "approved",
		discountPercent: 28,
		competitorMentioned: false,
		valueProof: "executive case",
		nextAction: "restate mutual plan milestone",
	},
	{
		id: "pricing-concession-021",
		account: "Brightline Media",
		owner: "Amelia",
		approvalStage: "rep-proposed",
		discountPercent: 31,
		competitorMentioned: false,
		valueProof: "usage trend",
		nextAction: "attach value proof",
	},
	{
		id: "pricing-concession-022",
		account: "Pioneer Manufacturing",
		owner: "Samir",
		approvalStage: "manager-review",
		discountPercent: 34,
		competitorMentioned: true,
		valueProof: "pilot win",
		nextAction: "request manager approval",
	},
	{
		id: "pricing-concession-023",
		account: "Northstar Health",
		owner: "Keiko",
		approvalStage: "finance-review",
		discountPercent: 37,
		competitorMentioned: false,
		valueProof: "security proof",
		nextAction: "confirm procurement owner",
	},
	{
		id: "pricing-concession-024",
		account: "Harbor Ledger",
		owner: "Leo",
		approvalStage: "approved",
		discountPercent: 6,
		competitorMentioned: false,
		valueProof: "executive case",
		nextAction: "restate mutual plan milestone",
	},
	{
		id: "pricing-concession-025",
		account: "Cedar Cloud",
		owner: "Amelia",
		approvalStage: "rep-proposed",
		discountPercent: 9,
		competitorMentioned: true,
		valueProof: "usage trend",
		nextAction: "attach value proof",
	},
	{
		id: "pricing-concession-026",
		account: "Summit Robotics",
		owner: "Samir",
		approvalStage: "manager-review",
		discountPercent: 12,
		competitorMentioned: false,
		valueProof: "pilot win",
		nextAction: "request manager approval",
	},
	{
		id: "pricing-concession-027",
		account: "Juniper Labs",
		owner: "Keiko",
		approvalStage: "finance-review",
		discountPercent: 15,
		competitorMentioned: false,
		valueProof: "security proof",
		nextAction: "confirm procurement owner",
	},
	{
		id: "pricing-concession-028",
		account: "Atlas Security",
		owner: "Leo",
		approvalStage: "approved",
		discountPercent: 18,
		competitorMentioned: true,
		valueProof: "executive case",
		nextAction: "restate mutual plan milestone",
	},
	{
		id: "pricing-concession-029",
		account: "Meridian Travel",
		owner: "Amelia",
		approvalStage: "rep-proposed",
		discountPercent: 21,
		competitorMentioned: false,
		valueProof: "usage trend",
		nextAction: "attach value proof",
	},
	{
		id: "pricing-concession-030",
		account: "Copper Grid",
		owner: "Samir",
		approvalStage: "manager-review",
		discountPercent: 24,
		competitorMentioned: false,
		valueProof: "pilot win",
		nextAction: "request manager approval",
	},
	{
		id: "pricing-concession-031",
		account: "Nimbus Legal",
		owner: "Keiko",
		approvalStage: "finance-review",
		discountPercent: 27,
		competitorMentioned: true,
		valueProof: "security proof",
		nextAction: "confirm procurement owner",
	},
	{
		id: "pricing-concession-032",
		account: "Aster Analytics",
		owner: "Leo",
		approvalStage: "approved",
		discountPercent: 30,
		competitorMentioned: false,
		valueProof: "executive case",
		nextAction: "restate mutual plan milestone",
	},
	{
		id: "pricing-concession-033",
		account: "Brightline Media",
		owner: "Amelia",
		approvalStage: "rep-proposed",
		discountPercent: 33,
		competitorMentioned: false,
		valueProof: "usage trend",
		nextAction: "attach value proof",
	},
	{
		id: "pricing-concession-034",
		account: "Pioneer Manufacturing",
		owner: "Samir",
		approvalStage: "manager-review",
		discountPercent: 36,
		competitorMentioned: true,
		valueProof: "pilot win",
		nextAction: "request manager approval",
	},
	{
		id: "pricing-concession-035",
		account: "Northstar Health",
		owner: "Keiko",
		approvalStage: "finance-review",
		discountPercent: 5,
		competitorMentioned: false,
		valueProof: "security proof",
		nextAction: "confirm procurement owner",
	},
	{
		id: "pricing-concession-036",
		account: "Harbor Ledger",
		owner: "Leo",
		approvalStage: "approved",
		discountPercent: 8,
		competitorMentioned: false,
		valueProof: "executive case",
		nextAction: "restate mutual plan milestone",
	},
	{
		id: "pricing-concession-037",
		account: "Cedar Cloud",
		owner: "Amelia",
		approvalStage: "rep-proposed",
		discountPercent: 11,
		competitorMentioned: true,
		valueProof: "usage trend",
		nextAction: "attach value proof",
	},
	{
		id: "pricing-concession-038",
		account: "Summit Robotics",
		owner: "Samir",
		approvalStage: "manager-review",
		discountPercent: 14,
		competitorMentioned: false,
		valueProof: "pilot win",
		nextAction: "request manager approval",
	},
	{
		id: "pricing-concession-039",
		account: "Juniper Labs",
		owner: "Keiko",
		approvalStage: "finance-review",
		discountPercent: 17,
		competitorMentioned: false,
		valueProof: "security proof",
		nextAction: "confirm procurement owner",
	},
	{
		id: "pricing-concession-040",
		account: "Atlas Security",
		owner: "Leo",
		approvalStage: "approved",
		discountPercent: 20,
		competitorMentioned: true,
		valueProof: "executive case",
		nextAction: "restate mutual plan milestone",
	},
	{
		id: "pricing-concession-041",
		account: "Meridian Travel",
		owner: "Amelia",
		approvalStage: "rep-proposed",
		discountPercent: 23,
		competitorMentioned: false,
		valueProof: "usage trend",
		nextAction: "attach value proof",
	},
	{
		id: "pricing-concession-042",
		account: "Copper Grid",
		owner: "Samir",
		approvalStage: "manager-review",
		discountPercent: 26,
		competitorMentioned: false,
		valueProof: "pilot win",
		nextAction: "request manager approval",
	},
	{
		id: "pricing-concession-043",
		account: "Nimbus Legal",
		owner: "Keiko",
		approvalStage: "finance-review",
		discountPercent: 29,
		competitorMentioned: true,
		valueProof: "security proof",
		nextAction: "confirm procurement owner",
	},
	{
		id: "pricing-concession-044",
		account: "Aster Analytics",
		owner: "Leo",
		approvalStage: "approved",
		discountPercent: 32,
		competitorMentioned: false,
		valueProof: "executive case",
		nextAction: "restate mutual plan milestone",
	},
	{
		id: "pricing-concession-045",
		account: "Brightline Media",
		owner: "Amelia",
		approvalStage: "rep-proposed",
		discountPercent: 35,
		competitorMentioned: false,
		valueProof: "usage trend",
		nextAction: "attach value proof",
	},
	{
		id: "pricing-concession-046",
		account: "Pioneer Manufacturing",
		owner: "Samir",
		approvalStage: "manager-review",
		discountPercent: 38,
		competitorMentioned: true,
		valueProof: "pilot win",
		nextAction: "request manager approval",
	},
	{
		id: "pricing-concession-047",
		account: "Northstar Health",
		owner: "Keiko",
		approvalStage: "finance-review",
		discountPercent: 7,
		competitorMentioned: false,
		valueProof: "security proof",
		nextAction: "confirm procurement owner",
	},
	{
		id: "pricing-concession-048",
		account: "Harbor Ledger",
		owner: "Leo",
		approvalStage: "approved",
		discountPercent: 10,
		competitorMentioned: false,
		valueProof: "executive case",
		nextAction: "restate mutual plan milestone",
	},
	{
		id: "pricing-concession-049",
		account: "Cedar Cloud",
		owner: "Amelia",
		approvalStage: "rep-proposed",
		discountPercent: 13,
		competitorMentioned: true,
		valueProof: "usage trend",
		nextAction: "attach value proof",
	},
	{
		id: "pricing-concession-050",
		account: "Summit Robotics",
		owner: "Samir",
		approvalStage: "manager-review",
		discountPercent: 16,
		competitorMentioned: false,
		valueProof: "pilot win",
		nextAction: "request manager approval",
	},
	{
		id: "pricing-concession-051",
		account: "Juniper Labs",
		owner: "Keiko",
		approvalStage: "finance-review",
		discountPercent: 19,
		competitorMentioned: false,
		valueProof: "security proof",
		nextAction: "confirm procurement owner",
	},
	{
		id: "pricing-concession-052",
		account: "Atlas Security",
		owner: "Leo",
		approvalStage: "approved",
		discountPercent: 22,
		competitorMentioned: true,
		valueProof: "executive case",
		nextAction: "restate mutual plan milestone",
	},
	{
		id: "pricing-concession-053",
		account: "Meridian Travel",
		owner: "Amelia",
		approvalStage: "rep-proposed",
		discountPercent: 25,
		competitorMentioned: false,
		valueProof: "usage trend",
		nextAction: "attach value proof",
	},
	{
		id: "pricing-concession-054",
		account: "Copper Grid",
		owner: "Samir",
		approvalStage: "manager-review",
		discountPercent: 28,
		competitorMentioned: false,
		valueProof: "pilot win",
		nextAction: "request manager approval",
	},
	{
		id: "pricing-concession-055",
		account: "Nimbus Legal",
		owner: "Keiko",
		approvalStage: "finance-review",
		discountPercent: 31,
		competitorMentioned: true,
		valueProof: "security proof",
		nextAction: "confirm procurement owner",
	},
	{
		id: "pricing-concession-056",
		account: "Aster Analytics",
		owner: "Leo",
		approvalStage: "approved",
		discountPercent: 34,
		competitorMentioned: false,
		valueProof: "executive case",
		nextAction: "restate mutual plan milestone",
	},
	{
		id: "pricing-concession-057",
		account: "Brightline Media",
		owner: "Amelia",
		approvalStage: "rep-proposed",
		discountPercent: 37,
		competitorMentioned: false,
		valueProof: "usage trend",
		nextAction: "attach value proof",
	},
	{
		id: "pricing-concession-058",
		account: "Pioneer Manufacturing",
		owner: "Samir",
		approvalStage: "manager-review",
		discountPercent: 6,
		competitorMentioned: true,
		valueProof: "pilot win",
		nextAction: "request manager approval",
	},
	{
		id: "pricing-concession-059",
		account: "Northstar Health",
		owner: "Keiko",
		approvalStage: "finance-review",
		discountPercent: 9,
		competitorMentioned: false,
		valueProof: "security proof",
		nextAction: "confirm procurement owner",
	},
	{
		id: "pricing-concession-060",
		account: "Harbor Ledger",
		owner: "Leo",
		approvalStage: "approved",
		discountPercent: 12,
		competitorMentioned: false,
		valueProof: "executive case",
		nextAction: "restate mutual plan milestone",
	},
	{
		id: "pricing-concession-061",
		account: "Cedar Cloud",
		owner: "Amelia",
		approvalStage: "rep-proposed",
		discountPercent: 15,
		competitorMentioned: true,
		valueProof: "usage trend",
		nextAction: "attach value proof",
	},
	{
		id: "pricing-concession-062",
		account: "Summit Robotics",
		owner: "Samir",
		approvalStage: "manager-review",
		discountPercent: 18,
		competitorMentioned: false,
		valueProof: "pilot win",
		nextAction: "request manager approval",
	},
	{
		id: "pricing-concession-063",
		account: "Juniper Labs",
		owner: "Keiko",
		approvalStage: "finance-review",
		discountPercent: 21,
		competitorMentioned: false,
		valueProof: "security proof",
		nextAction: "confirm procurement owner",
	},
	{
		id: "pricing-concession-064",
		account: "Atlas Security",
		owner: "Leo",
		approvalStage: "approved",
		discountPercent: 24,
		competitorMentioned: true,
		valueProof: "executive case",
		nextAction: "restate mutual plan milestone",
	},
	{
		id: "pricing-concession-065",
		account: "Meridian Travel",
		owner: "Amelia",
		approvalStage: "rep-proposed",
		discountPercent: 27,
		competitorMentioned: false,
		valueProof: "usage trend",
		nextAction: "attach value proof",
	},
	{
		id: "pricing-concession-066",
		account: "Copper Grid",
		owner: "Samir",
		approvalStage: "manager-review",
		discountPercent: 30,
		competitorMentioned: false,
		valueProof: "pilot win",
		nextAction: "request manager approval",
	},
	{
		id: "pricing-concession-067",
		account: "Nimbus Legal",
		owner: "Keiko",
		approvalStage: "finance-review",
		discountPercent: 33,
		competitorMentioned: true,
		valueProof: "security proof",
		nextAction: "confirm procurement owner",
	},
	{
		id: "pricing-concession-068",
		account: "Aster Analytics",
		owner: "Leo",
		approvalStage: "approved",
		discountPercent: 36,
		competitorMentioned: false,
		valueProof: "executive case",
		nextAction: "restate mutual plan milestone",
	},
];

export function summarizePricingConcessions(
	scenarios: readonly PricingConcessionScenario[] = pricingConcessionScenarios,
): PricingConcessionSummary {
	const averageDiscount = average(scenarios.map((scenario) => scenario.discountPercent));
	const financeReview = scenarios.filter((scenario) => scenario.approvalStage === "finance-review").length;
	const competitorPressure = scenarios.filter((scenario) => scenario.competitorMentioned).length;
	return {
		scenarios: scenarios.length,
		averageDiscount,
		financeReview,
		competitorPressure,
		owners: unique(scenarios.map((scenario) => scenario.owner)),
		requiredActions: unique(scenarios.filter((scenario) => scenario.discountPercent >= 20).map((scenario) => scenario.nextAction)),
	};
}

export function findPricingConcessionsByStage(
	stage: PricingApprovalStage,
	scenarios: readonly PricingConcessionScenario[] = pricingConcessionScenarios,
): readonly PricingConcessionScenario[] {
	return scenarios.filter((scenario) => scenario.approvalStage === stage);
}

export function renderPricingConcessionSummary(summary: PricingConcessionSummary): string {
	return [
		"pricing concession tracker",
		`Scenarios: ${summary.scenarios}`,
		`Average discount: ${summary.averageDiscount}%`,
		`Finance review: ${summary.financeReview}`,
		`Competitor pressure: ${summary.competitorPressure}`,
		`Required actions: ${summary.requiredActions.join("; ")}`,
	].join("\n");
}

function average(values: readonly number[]): number {
	if (values.length === 0) {
		return 0;
	}
	return Math.round((values.reduce((sum, value) => sum + value, 0) / values.length) * 10) / 10;
}

function unique(values: readonly string[]): readonly string[] {
	return [...new Set(values)].sort();
}
