export type StakeholderGapRisk = "low" | "medium" | "high";

export interface StakeholderGapScenario {
	readonly id: string;
	readonly account: string;
	readonly owner: string;
	readonly persona: string;
	readonly risk: StakeholderGapRisk;
	readonly gapAgeDays: number;
	readonly lastSignal: string;
	readonly nextAction: string;
}

export interface StakeholderGapSummary {
	readonly scenarios: number;
	readonly highRisk: number;
	readonly staleGaps: number;
	readonly owners: readonly string[];
	readonly personas: readonly string[];
	readonly nextActions: readonly string[];
}

export const stakeholderGapScenarios: readonly StakeholderGapScenario[] = [
	{
		id: "stakeholder-gap-001",
		account: "Northstar Health",
		owner: "Maya",
		persona: "economic buyer",
		risk: "low",
		gapAgeDays: 0,
		lastSignal: "champion asked for a stronger rollout story",
		nextAction: "schedule stakeholder map refresh",
	},
	{
		id: "stakeholder-gap-002",
		account: "Harbor Ledger",
		owner: "Jon",
		persona: "technical sponsor",
		risk: "medium",
		gapAgeDays: 4,
		lastSignal: "security reviewer reopened the data retention topic",
		nextAction: "send proof packet",
	},
	{
		id: "stakeholder-gap-003",
		account: "Cedar Cloud",
		owner: "Priya",
		persona: "security reviewer",
		risk: "high",
		gapAgeDays: 8,
		lastSignal: "economic buyer skipped the mutual plan review",
		nextAction: "book executive alignment call",
	},
	{
		id: "stakeholder-gap-004",
		account: "Summit Robotics",
		owner: "Nora",
		persona: "business champion",
		risk: "low",
		gapAgeDays: 12,
		lastSignal: "technical sponsor requested integration proof",
		nextAction: "publish replay clip",
	},
	{
		id: "stakeholder-gap-005",
		account: "Juniper Labs",
		owner: "Maya",
		persona: "economic buyer",
		risk: "medium",
		gapAgeDays: 16,
		lastSignal: "champion asked for a stronger rollout story",
		nextAction: "schedule stakeholder map refresh",
	},
	{
		id: "stakeholder-gap-006",
		account: "Atlas Security",
		owner: "Jon",
		persona: "technical sponsor",
		risk: "high",
		gapAgeDays: 20,
		lastSignal: "security reviewer reopened the data retention topic",
		nextAction: "send proof packet",
	},
	{
		id: "stakeholder-gap-007",
		account: "Meridian Travel",
		owner: "Priya",
		persona: "security reviewer",
		risk: "low",
		gapAgeDays: 24,
		lastSignal: "economic buyer skipped the mutual plan review",
		nextAction: "book executive alignment call",
	},
	{
		id: "stakeholder-gap-008",
		account: "Copper Grid",
		owner: "Nora",
		persona: "business champion",
		risk: "medium",
		gapAgeDays: 28,
		lastSignal: "technical sponsor requested integration proof",
		nextAction: "publish replay clip",
	},
	{
		id: "stakeholder-gap-009",
		account: "Nimbus Legal",
		owner: "Maya",
		persona: "economic buyer",
		risk: "high",
		gapAgeDays: 1,
		lastSignal: "champion asked for a stronger rollout story",
		nextAction: "schedule stakeholder map refresh",
	},
	{
		id: "stakeholder-gap-010",
		account: "Aster Analytics",
		owner: "Jon",
		persona: "technical sponsor",
		risk: "low",
		gapAgeDays: 5,
		lastSignal: "security reviewer reopened the data retention topic",
		nextAction: "send proof packet",
	},
	{
		id: "stakeholder-gap-011",
		account: "Brightline Media",
		owner: "Priya",
		persona: "security reviewer",
		risk: "medium",
		gapAgeDays: 9,
		lastSignal: "economic buyer skipped the mutual plan review",
		nextAction: "book executive alignment call",
	},
	{
		id: "stakeholder-gap-012",
		account: "Pioneer Manufacturing",
		owner: "Nora",
		persona: "business champion",
		risk: "high",
		gapAgeDays: 13,
		lastSignal: "technical sponsor requested integration proof",
		nextAction: "publish replay clip",
	},
	{
		id: "stakeholder-gap-013",
		account: "Northstar Health",
		owner: "Maya",
		persona: "economic buyer",
		risk: "low",
		gapAgeDays: 17,
		lastSignal: "champion asked for a stronger rollout story",
		nextAction: "schedule stakeholder map refresh",
	},
	{
		id: "stakeholder-gap-014",
		account: "Harbor Ledger",
		owner: "Jon",
		persona: "technical sponsor",
		risk: "medium",
		gapAgeDays: 21,
		lastSignal: "security reviewer reopened the data retention topic",
		nextAction: "send proof packet",
	},
	{
		id: "stakeholder-gap-015",
		account: "Cedar Cloud",
		owner: "Priya",
		persona: "security reviewer",
		risk: "high",
		gapAgeDays: 25,
		lastSignal: "economic buyer skipped the mutual plan review",
		nextAction: "book executive alignment call",
	},
	{
		id: "stakeholder-gap-016",
		account: "Summit Robotics",
		owner: "Nora",
		persona: "business champion",
		risk: "low",
		gapAgeDays: 29,
		lastSignal: "technical sponsor requested integration proof",
		nextAction: "publish replay clip",
	},
	{
		id: "stakeholder-gap-017",
		account: "Juniper Labs",
		owner: "Maya",
		persona: "economic buyer",
		risk: "medium",
		gapAgeDays: 2,
		lastSignal: "champion asked for a stronger rollout story",
		nextAction: "schedule stakeholder map refresh",
	},
	{
		id: "stakeholder-gap-018",
		account: "Atlas Security",
		owner: "Jon",
		persona: "technical sponsor",
		risk: "high",
		gapAgeDays: 6,
		lastSignal: "security reviewer reopened the data retention topic",
		nextAction: "send proof packet",
	},
	{
		id: "stakeholder-gap-019",
		account: "Meridian Travel",
		owner: "Priya",
		persona: "security reviewer",
		risk: "low",
		gapAgeDays: 10,
		lastSignal: "economic buyer skipped the mutual plan review",
		nextAction: "book executive alignment call",
	},
	{
		id: "stakeholder-gap-020",
		account: "Copper Grid",
		owner: "Nora",
		persona: "business champion",
		risk: "medium",
		gapAgeDays: 14,
		lastSignal: "technical sponsor requested integration proof",
		nextAction: "publish replay clip",
	},
	{
		id: "stakeholder-gap-021",
		account: "Nimbus Legal",
		owner: "Maya",
		persona: "economic buyer",
		risk: "high",
		gapAgeDays: 18,
		lastSignal: "champion asked for a stronger rollout story",
		nextAction: "schedule stakeholder map refresh",
	},
	{
		id: "stakeholder-gap-022",
		account: "Aster Analytics",
		owner: "Jon",
		persona: "technical sponsor",
		risk: "low",
		gapAgeDays: 22,
		lastSignal: "security reviewer reopened the data retention topic",
		nextAction: "send proof packet",
	},
	{
		id: "stakeholder-gap-023",
		account: "Brightline Media",
		owner: "Priya",
		persona: "security reviewer",
		risk: "medium",
		gapAgeDays: 26,
		lastSignal: "economic buyer skipped the mutual plan review",
		nextAction: "book executive alignment call",
	},
	{
		id: "stakeholder-gap-024",
		account: "Pioneer Manufacturing",
		owner: "Nora",
		persona: "business champion",
		risk: "high",
		gapAgeDays: 30,
		lastSignal: "technical sponsor requested integration proof",
		nextAction: "publish replay clip",
	},
	{
		id: "stakeholder-gap-025",
		account: "Northstar Health",
		owner: "Maya",
		persona: "economic buyer",
		risk: "low",
		gapAgeDays: 3,
		lastSignal: "champion asked for a stronger rollout story",
		nextAction: "schedule stakeholder map refresh",
	},
	{
		id: "stakeholder-gap-026",
		account: "Harbor Ledger",
		owner: "Jon",
		persona: "technical sponsor",
		risk: "medium",
		gapAgeDays: 7,
		lastSignal: "security reviewer reopened the data retention topic",
		nextAction: "send proof packet",
	},
	{
		id: "stakeholder-gap-027",
		account: "Cedar Cloud",
		owner: "Priya",
		persona: "security reviewer",
		risk: "high",
		gapAgeDays: 11,
		lastSignal: "economic buyer skipped the mutual plan review",
		nextAction: "book executive alignment call",
	},
	{
		id: "stakeholder-gap-028",
		account: "Summit Robotics",
		owner: "Nora",
		persona: "business champion",
		risk: "low",
		gapAgeDays: 15,
		lastSignal: "technical sponsor requested integration proof",
		nextAction: "publish replay clip",
	},
	{
		id: "stakeholder-gap-029",
		account: "Juniper Labs",
		owner: "Maya",
		persona: "economic buyer",
		risk: "medium",
		gapAgeDays: 19,
		lastSignal: "champion asked for a stronger rollout story",
		nextAction: "schedule stakeholder map refresh",
	},
	{
		id: "stakeholder-gap-030",
		account: "Atlas Security",
		owner: "Jon",
		persona: "technical sponsor",
		risk: "high",
		gapAgeDays: 23,
		lastSignal: "security reviewer reopened the data retention topic",
		nextAction: "send proof packet",
	},
	{
		id: "stakeholder-gap-031",
		account: "Meridian Travel",
		owner: "Priya",
		persona: "security reviewer",
		risk: "low",
		gapAgeDays: 27,
		lastSignal: "economic buyer skipped the mutual plan review",
		nextAction: "book executive alignment call",
	},
	{
		id: "stakeholder-gap-032",
		account: "Copper Grid",
		owner: "Nora",
		persona: "business champion",
		risk: "medium",
		gapAgeDays: 0,
		lastSignal: "technical sponsor requested integration proof",
		nextAction: "publish replay clip",
	},
	{
		id: "stakeholder-gap-033",
		account: "Nimbus Legal",
		owner: "Maya",
		persona: "economic buyer",
		risk: "high",
		gapAgeDays: 4,
		lastSignal: "champion asked for a stronger rollout story",
		nextAction: "schedule stakeholder map refresh",
	},
	{
		id: "stakeholder-gap-034",
		account: "Aster Analytics",
		owner: "Jon",
		persona: "technical sponsor",
		risk: "low",
		gapAgeDays: 8,
		lastSignal: "security reviewer reopened the data retention topic",
		nextAction: "send proof packet",
	},
	{
		id: "stakeholder-gap-035",
		account: "Brightline Media",
		owner: "Priya",
		persona: "security reviewer",
		risk: "medium",
		gapAgeDays: 12,
		lastSignal: "economic buyer skipped the mutual plan review",
		nextAction: "book executive alignment call",
	},
	{
		id: "stakeholder-gap-036",
		account: "Pioneer Manufacturing",
		owner: "Nora",
		persona: "business champion",
		risk: "high",
		gapAgeDays: 16,
		lastSignal: "technical sponsor requested integration proof",
		nextAction: "publish replay clip",
	},
	{
		id: "stakeholder-gap-037",
		account: "Northstar Health",
		owner: "Maya",
		persona: "economic buyer",
		risk: "low",
		gapAgeDays: 20,
		lastSignal: "champion asked for a stronger rollout story",
		nextAction: "schedule stakeholder map refresh",
	},
	{
		id: "stakeholder-gap-038",
		account: "Harbor Ledger",
		owner: "Jon",
		persona: "technical sponsor",
		risk: "medium",
		gapAgeDays: 24,
		lastSignal: "security reviewer reopened the data retention topic",
		nextAction: "send proof packet",
	},
	{
		id: "stakeholder-gap-039",
		account: "Cedar Cloud",
		owner: "Priya",
		persona: "security reviewer",
		risk: "high",
		gapAgeDays: 28,
		lastSignal: "economic buyer skipped the mutual plan review",
		nextAction: "book executive alignment call",
	},
	{
		id: "stakeholder-gap-040",
		account: "Summit Robotics",
		owner: "Nora",
		persona: "business champion",
		risk: "low",
		gapAgeDays: 1,
		lastSignal: "technical sponsor requested integration proof",
		nextAction: "publish replay clip",
	},
	{
		id: "stakeholder-gap-041",
		account: "Juniper Labs",
		owner: "Maya",
		persona: "economic buyer",
		risk: "medium",
		gapAgeDays: 5,
		lastSignal: "champion asked for a stronger rollout story",
		nextAction: "schedule stakeholder map refresh",
	},
	{
		id: "stakeholder-gap-042",
		account: "Atlas Security",
		owner: "Jon",
		persona: "technical sponsor",
		risk: "high",
		gapAgeDays: 9,
		lastSignal: "security reviewer reopened the data retention topic",
		nextAction: "send proof packet",
	},
	{
		id: "stakeholder-gap-043",
		account: "Meridian Travel",
		owner: "Priya",
		persona: "security reviewer",
		risk: "low",
		gapAgeDays: 13,
		lastSignal: "economic buyer skipped the mutual plan review",
		nextAction: "book executive alignment call",
	},
	{
		id: "stakeholder-gap-044",
		account: "Copper Grid",
		owner: "Nora",
		persona: "business champion",
		risk: "medium",
		gapAgeDays: 17,
		lastSignal: "technical sponsor requested integration proof",
		nextAction: "publish replay clip",
	},
	{
		id: "stakeholder-gap-045",
		account: "Nimbus Legal",
		owner: "Maya",
		persona: "economic buyer",
		risk: "high",
		gapAgeDays: 21,
		lastSignal: "champion asked for a stronger rollout story",
		nextAction: "schedule stakeholder map refresh",
	},
	{
		id: "stakeholder-gap-046",
		account: "Aster Analytics",
		owner: "Jon",
		persona: "technical sponsor",
		risk: "low",
		gapAgeDays: 25,
		lastSignal: "security reviewer reopened the data retention topic",
		nextAction: "send proof packet",
	},
	{
		id: "stakeholder-gap-047",
		account: "Brightline Media",
		owner: "Priya",
		persona: "security reviewer",
		risk: "medium",
		gapAgeDays: 29,
		lastSignal: "economic buyer skipped the mutual plan review",
		nextAction: "book executive alignment call",
	},
	{
		id: "stakeholder-gap-048",
		account: "Pioneer Manufacturing",
		owner: "Nora",
		persona: "business champion",
		risk: "high",
		gapAgeDays: 2,
		lastSignal: "technical sponsor requested integration proof",
		nextAction: "publish replay clip",
	},
	{
		id: "stakeholder-gap-049",
		account: "Northstar Health",
		owner: "Maya",
		persona: "economic buyer",
		risk: "low",
		gapAgeDays: 6,
		lastSignal: "champion asked for a stronger rollout story",
		nextAction: "schedule stakeholder map refresh",
	},
	{
		id: "stakeholder-gap-050",
		account: "Harbor Ledger",
		owner: "Jon",
		persona: "technical sponsor",
		risk: "medium",
		gapAgeDays: 10,
		lastSignal: "security reviewer reopened the data retention topic",
		nextAction: "send proof packet",
	},
	{
		id: "stakeholder-gap-051",
		account: "Cedar Cloud",
		owner: "Priya",
		persona: "security reviewer",
		risk: "high",
		gapAgeDays: 14,
		lastSignal: "economic buyer skipped the mutual plan review",
		nextAction: "book executive alignment call",
	},
	{
		id: "stakeholder-gap-052",
		account: "Summit Robotics",
		owner: "Nora",
		persona: "business champion",
		risk: "low",
		gapAgeDays: 18,
		lastSignal: "technical sponsor requested integration proof",
		nextAction: "publish replay clip",
	},
	{
		id: "stakeholder-gap-053",
		account: "Juniper Labs",
		owner: "Maya",
		persona: "economic buyer",
		risk: "medium",
		gapAgeDays: 22,
		lastSignal: "champion asked for a stronger rollout story",
		nextAction: "schedule stakeholder map refresh",
	},
	{
		id: "stakeholder-gap-054",
		account: "Atlas Security",
		owner: "Jon",
		persona: "technical sponsor",
		risk: "high",
		gapAgeDays: 26,
		lastSignal: "security reviewer reopened the data retention topic",
		nextAction: "send proof packet",
	},
	{
		id: "stakeholder-gap-055",
		account: "Meridian Travel",
		owner: "Priya",
		persona: "security reviewer",
		risk: "low",
		gapAgeDays: 30,
		lastSignal: "economic buyer skipped the mutual plan review",
		nextAction: "book executive alignment call",
	},
	{
		id: "stakeholder-gap-056",
		account: "Copper Grid",
		owner: "Nora",
		persona: "business champion",
		risk: "medium",
		gapAgeDays: 3,
		lastSignal: "technical sponsor requested integration proof",
		nextAction: "publish replay clip",
	},
	{
		id: "stakeholder-gap-057",
		account: "Nimbus Legal",
		owner: "Maya",
		persona: "economic buyer",
		risk: "high",
		gapAgeDays: 7,
		lastSignal: "champion asked for a stronger rollout story",
		nextAction: "schedule stakeholder map refresh",
	},
	{
		id: "stakeholder-gap-058",
		account: "Aster Analytics",
		owner: "Jon",
		persona: "technical sponsor",
		risk: "low",
		gapAgeDays: 11,
		lastSignal: "security reviewer reopened the data retention topic",
		nextAction: "send proof packet",
	},
	{
		id: "stakeholder-gap-059",
		account: "Brightline Media",
		owner: "Priya",
		persona: "security reviewer",
		risk: "medium",
		gapAgeDays: 15,
		lastSignal: "economic buyer skipped the mutual plan review",
		nextAction: "book executive alignment call",
	},
	{
		id: "stakeholder-gap-060",
		account: "Pioneer Manufacturing",
		owner: "Nora",
		persona: "business champion",
		risk: "high",
		gapAgeDays: 19,
		lastSignal: "technical sponsor requested integration proof",
		nextAction: "publish replay clip",
	},
	{
		id: "stakeholder-gap-061",
		account: "Northstar Health",
		owner: "Maya",
		persona: "economic buyer",
		risk: "low",
		gapAgeDays: 23,
		lastSignal: "champion asked for a stronger rollout story",
		nextAction: "schedule stakeholder map refresh",
	},
	{
		id: "stakeholder-gap-062",
		account: "Harbor Ledger",
		owner: "Jon",
		persona: "technical sponsor",
		risk: "medium",
		gapAgeDays: 27,
		lastSignal: "security reviewer reopened the data retention topic",
		nextAction: "send proof packet",
	},
	{
		id: "stakeholder-gap-063",
		account: "Cedar Cloud",
		owner: "Priya",
		persona: "security reviewer",
		risk: "high",
		gapAgeDays: 0,
		lastSignal: "economic buyer skipped the mutual plan review",
		nextAction: "book executive alignment call",
	},
	{
		id: "stakeholder-gap-064",
		account: "Summit Robotics",
		owner: "Nora",
		persona: "business champion",
		risk: "low",
		gapAgeDays: 4,
		lastSignal: "technical sponsor requested integration proof",
		nextAction: "publish replay clip",
	},
];

export function summarizeStakeholderGaps(
	scenarios: readonly StakeholderGapScenario[] = stakeholderGapScenarios,
): StakeholderGapSummary {
	const highRisk = scenarios.filter((scenario) => scenario.risk === "high").length;
	const staleGaps = scenarios.filter((scenario) => scenario.gapAgeDays >= 14).length;
	return {
		scenarios: scenarios.length,
		highRisk,
		staleGaps,
		owners: unique(scenarios.map((scenario) => scenario.owner)),
		personas: unique(scenarios.map((scenario) => scenario.persona)),
		nextActions: unique(scenarios.filter((scenario) => scenario.risk !== "low").map((scenario) => scenario.nextAction)),
	};
}

export function filterStakeholderGapsByOwner(
	owner: string,
	scenarios: readonly StakeholderGapScenario[] = stakeholderGapScenarios,
): readonly StakeholderGapScenario[] {
	return scenarios.filter((scenario) => scenario.owner.toLowerCase() === owner.toLowerCase());
}

export function renderStakeholderGapSummary(summary: StakeholderGapSummary): string {
	return [
		"stakeholder gap board",
		`Scenarios: ${summary.scenarios}`,
		`High risk: ${summary.highRisk}`,
		`Stale gaps: ${summary.staleGaps}`,
		`Owners: ${summary.owners.join(", ")}`,
		`Next actions: ${summary.nextActions.join("; ")}`,
	].join("\n");
}

function unique(values: readonly string[]): readonly string[] {
	return [...new Set(values)].sort();
}
